apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-ebs-volume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  awsElasticBlockStore:
    volumeID: vol-0718f2aaa96d3d655
    fsType: ext4

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: zone
          operator: In
          values:
          - us-east-1a